/* Cloudflare Worker: receives one study response and commits it to the repo.
 *
 * The GitHub token lives only here, as a Worker secret. It is never sent to the
 * browser, so the static site can stay on GitHub Pages with no credentials in
 * it. Configure with:
 *
 *   wrangler secret put GITHUB_TOKEN      # fine-grained PAT, Contents: R/W
 *   wrangler deploy
 *
 * Environment (see wrangler.toml for the non-secret ones):
 *   GITHUB_TOKEN   secret. Fine-grained PAT scoped to this repo only.
 *   GITHUB_REPO    "owner/name"
 *   GITHUB_BRANCH  branch to commit to, e.g. "main"
 *   ALLOWED_ORIGIN exact origin of the study site, e.g.
 *                  "https://owner.github.io". Requests from anywhere else are
 *                  refused, which keeps the endpoint from being used as an
 *                  open write channel into the repo.
 */

const MAX_BODY_BYTES = 256 * 1024;
const CRITERIA = ["overall", "penetration", "semantic"];

/* ------------------------------------------------------------ validation */

/** Reject anything that is not a well-formed response document.
 *  Everything written to the repo passes through here first: the payload is
 *  attacker-controlled, so it is validated rather than trusted. */
function validate(payload) {
  if (payload === null || typeof payload !== "object" || Array.isArray(payload)) {
    return "payload must be an object";
  }
  if (payload.schema !== "refm-user-study/v1") return "unknown schema";

  if (typeof payload.participantId !== "string" ||
      !/^[0-9a-f-]{36}$/i.test(payload.participantId)) {
    return "participantId must be a uuid";
  }
  for (const key of ["startedAt", "submittedAt"]) {
    if (typeof payload[key] !== "string" || Number.isNaN(Date.parse(payload[key]))) {
      return `${key} must be an ISO timestamp`;
    }
  }
  if (!Array.isArray(payload.clips) || payload.clips.length === 0 ||
      payload.clips.length > 100) {
    return "clips must be a non-empty array of at most 100 entries";
  }

  for (const clip of payload.clips) {
    if (clip === null || typeof clip !== "object") return "clip must be an object";
    if (typeof clip.clipId !== "string" || clip.clipId.length > 200) {
      return "clipId must be a short string";
    }
    if (clip.order === null || typeof clip.order !== "object") {
      return "clip.order must be an object";
    }
    if (clip.ranks === null || typeof clip.ranks !== "object") {
      return "clip.ranks must be an object";
    }
    for (const crit of Object.keys(clip.ranks)) {
      if (!CRITERIA.includes(crit)) return `unknown criterion ${crit}`;
      const byMethod = clip.ranks[crit];
      if (byMethod === null || typeof byMethod !== "object") {
        return "ranks[criterion] must be an object";
      }
      for (const method of Object.keys(byMethod)) {
        const rank = byMethod[method];
        if (!Number.isInteger(rank) || rank < 1 || rank > 20) {
          return "each rank must be an integer between 1 and 20";
        }
      }
    }
  }

  if (payload.comments !== undefined &&
      (typeof payload.comments !== "string" || payload.comments.length > 2000)) {
    return "comments must be a string of at most 2000 characters";
  }
  if (payload.expertise !== undefined && typeof payload.expertise !== "string") {
    return "expertise must be a string";
  }
  return null;
}

/* ---------------------------------------------------------------- github */

function b64(text) {
  const bytes = new TextEncoder().encode(text);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

async function commitResponse(env, filename, contents) {
  // `filename` is generated by us, never taken from the request body, so the
  // committed path cannot be steered by a participant.
  const url = `https://api.github.com/repos/${env.GITHUB_REPO}` +
              `/contents/results/responses/${filename}`;
  const res = await fetch(url, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "refm-user-study-worker",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      message: `study: response ${filename}`,
      content: b64(contents),
      branch: env.GITHUB_BRANCH || "main",
    }),
  });
  if (!res.ok) {
    // Surface status only; the GitHub error body can echo repo details.
    throw new Error(`github api ${res.status}`);
  }
}

/* ----------------------------------------------------------------- http */

function corsHeaders(env) {
  return {
    "Access-Control-Allow-Origin": env.ALLOWED_ORIGIN || "",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Max-Age": "86400",
    Vary: "Origin",
  };
}

function json(body, status, env) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(env) },
  });
}

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders(env) });
    }
    if (request.method !== "POST") {
      return json({ error: "method not allowed" }, 405, env);
    }

    const origin = request.headers.get("Origin");
    if (typeof env.ALLOWED_ORIGIN === "string" && env.ALLOWED_ORIGIN !== "" &&
        origin !== env.ALLOWED_ORIGIN) {
      return json({ error: "origin not allowed" }, 403, env);
    }

    const raw = await request.text();
    if (raw.length > MAX_BODY_BYTES) {
      return json({ error: "payload too large" }, 413, env);
    }

    let payload;
    try {
      payload = JSON.parse(raw);
    } catch (_) {
      return json({ error: "invalid json" }, 400, env);
    }

    const problem = validate(payload);
    if (problem !== null) return json({ error: problem }, 400, env);

    // Server-generated filename: sortable, unique, and not attacker-influenced.
    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    const filename = `${stamp}-${crypto.randomUUID()}.json`;

    try {
      await commitResponse(env, filename, JSON.stringify(payload, null, 2) + "\n");
    } catch (err) {
      return json({ error: "could not store response" }, 502, env);
    }
    return json({ ok: true }, 200, env);
  },
};
